### ISSUE TITLE
Crash when the program exit: ProcessTerminatedError: cancel after 0 retries!

### ISSUE THREAD

**Issue by jagu-sayan** [allegro/node-worker-nodes#23]
On circleci, my program crash at onExit callback.
The program work on local environement.

Edit: A worker crash, but I don't know how to get more error output. It's seems like the real error is hidden by node-worker-nodes :/

I use node v8.7.0 and npm v5.5.1

![image](https://user-images.githubusercontent.com/1262860/31991115-41d22e8a-b977-11e7-878e-0cd5cbb05434.png)

```sh
> ERROR: ProcessTerminatedError: cancel after 0 retries!
    at tasks.filter.forEach.task (/home/circleci/project/node_modules/worker-nodes/lib/pool.js:111:39)
    at Array.forEach (<anonymous>)
    at WorkerNodes.handleWorkerExit (/home/circleci/project/node_modules/worker-nodes/lib/pool.js:110:14)
    at Worker.worker.on.exitCode (/home/circleci/project/node_modules/worker-nodes/lib/pool.js:160:44)
    at emitOne (events.js:115:13)
    at Worker.emit (events.js:210:7)
    at WorkerProcess.Worker.process.once.code (/home/circleci/project/node_modules/worker-nodes/lib/worker.js:39:18)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at WorkerProcess.emit (events.js:210:7)
    at ChildProcess.WorkerProcess.child.once.code (/home/circleci/project/node_modules/worker-nodes/lib/worker/process.js:42:41)
    at Object.onceWrapper (events.js:318:30)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

{ Error: read ECONNRESET
    at _errnoException (util.js:1021:11)
    at Pipe.onread (net.js:608:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
{ Error: read ECONNRESET
    at _errnoException (util.js:1021:11)
    at Pipe.onread (net.js:608:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
{ Error: read ECONNRESET
    at _errnoException (util.js:1021:11)
    at Pipe.onread (net.js:608:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
{ Error: read ECONNRESET
    at _errnoException (util.js:1021:11)
    at Pipe.onread (net.js:608:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
{ Error: read ECONNRESET
    at _errnoException (util.js:1021:11)
    at Pipe.onread (net.js:608:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
{ Error: read ECONNRESET
    at _errnoException (util.js:1021:11)
    at Pipe.onread (net.js:608:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
{ Error: read ECONNRESET
    at _errnoException (util.js:1021:11)
    at Pipe.onread (net.js:608:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
{ Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:354:12)
    at Transport.send (/home/circleci/project/node_modules/worker-nodes/lib/worker/transport.js:57:19)
    at Promise.then.result (/home/circleci/project/node_modules/worker-nodes/lib/worker/child-loader.js:36:28)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) code: 'EPIPE' }
```

**Comment by jagu-sayan** [comment]
It because the default value of `workerStopTimeout` was too low. I set the value to 1s and the problem disapear 😄
